# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71be55b0bb45be88bf8c31cf1b1873e9f35475046b559a820921d52122ac1feb4da24caf7d01aa238eb667051e3528fff1061eb7edca9eb145cb7e3c5bf32e05

test:
  secret_key_base: 8c2d95819c5b170432b6d66a197b5d61249af37dc2c81e4fb7619cf13702aeb2966e7827488038b4100732f335ac61271cad35dd83c84ffbdeb5e02ca4b0e532

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
